name: Publish Package

on:
  push:
    tags:
      - 'v*'

permissions:
  id-token: write
  contents: read

jobs:
  publish:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        node-version: [24]

    steps:
      - uses: actions/checkout@v6
        with:
          ref: main

      - name: 安装 pnpm
        uses: pnpm/action-setup@8912a9102ac27614460f54aedde9e1e7f9aec20d # v6.0.5
        with:
          version: 11

      - name: 使用 Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - run: pnpm install

      - run: pnpm run build

      - run: pnpm publish
